name: senly
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0-134.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  yandex_mapkit: ^3.3.3
  geolocator: ^10.1.0
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  mqtt_client: ^10.0.0
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  firebase_database: ^10.0.15
  cloud_firestore: ^4.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/


  fonts:
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/lexend_deca/LexendDeca-Black.ttf
          weight: 900
        - asset: assets/fonts/lexend_deca/LexendDeca-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/lexend_deca/LexendDeca-Bold.ttf
          weight: 700
        - asset: assets/fonts/lexend_deca/LexendDeca-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/lexend_deca/LexendDeca-Medium.ttf
          weight: 500
        - asset: assets/fonts/lexend_deca/LexendDeca-Regular.ttf
          weight: 400
        - asset: assets/fonts/lexend_deca/LexendDeca-Light.ttf
          weight: 300
        - asset: assets/fonts/lexend_deca/LexendDeca-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/lexend_deca/LexendDeca-Thin.ttf
          weight: 100